### ISSUE TITLE
Time error

### ISSUE THREAD

**Issue by ddzzkunye** [oookoook/NighttimeDisplayDimmer#1]
It is now 18:54 in the +8 time zone.
But
![image](https://user-images.githubusercontent.com/92249100/220326004-866264ca-b6cc-4c0f-a3e1-a48b4ea0fad2.png)
Day Currently active

**Comment by oookoook** [comment]
Hello, the Night/Day switch is not controlled directly by the daytime. Instead, it is controlled by the Windows function Night light. Try to turn it on, and it will switch the app mode. The steps are described here: https://sunsetdimmer.nastojte.cz/help/

**Comment by ddzzkunye** [comment]
I know, thank you.
